### ISSUE TITLE
Hello, May I ask a few questions? project.tracks[0].notes.tickOn what's the unit? and....

### ISSUE THREAD

**Issue by zhaoleicpp** [sdercolin/utaformatix-data#1]
你好，我能不能问几个问题？
Hello, May I ask a few questions?
project.tracks[0].notes.tickOn 的单位是啥? 毫秒，还是beat时间/n，n是多少？
project.tracks[0].notes.tickOn what's the unit? millisecond? or (beat time)/n, what is n?
project.tracks[0].notes.phoneme 哪种音标，国际音标ipa，还是 x-sampa
project.tracks[0].notes.phoneme, which phonetic symbol? IPA or x-sampa?
project.tracks[0].notes.lyric 对于汉字是放汉语拼音还是汉字？
project.tracks[0].notes.lyric, To Chinese,  is lyric the Chinese character or "Chinese pinyin"?
如何处理连音（滑音），能不能给个例子
How to record legato(portamento，slur cutter),  will you please give me an example.

请将答案记录在README.md里
Will you please modify the README.md using the answers?

**Comment by sdercolin** [comment]
tick是MIDI的时间单位，一般情况下1beat=480ticks
tick和秒的转换需要借助bpm，在bpm稳定的区间内：
假设BPM是120，也就是 120 beats per minute:
1s = 1/60 min = 120/60 beats= 2 beats = 2* 480 ticks = 960 ticks

phoneme和lyric，ufdata格式上没有给规定，只是给了这两个field，因为各个SVS系统的要求都不同，无法统一。
请根据需要自行转换。（UtaFormatix有一些歌词转换的功能可以尝试使用。音素转换的功能正在做。）

连音（滑音）暂时没有对应的字段。类MIDI的格式中不太多见到这个信息，如果要求存储这类乐谱信息，可以考虑使用MusicXML。

**Comment by zhaoleicpp** [comment]
建议连音用⌒字符。

**Comment by zhaoleicpp** [comment]
多谢
